### ISSUE TITLE
Interfaces 

### ISSUE THREAD

**Issue by EmilyLip** [barnahum8/YouAteIt#9]
https://github.com/barnahum8/YouAteIt/blob/9ad092617cab9d5005eba075fb3961831da4fafc/client/my-app/src/components/FormComp/FormComp.tsx#L12

Use Significant  Interfaces names, additionally it's customary to use models folder and set the interfaces there.
In this way you can use those interfaces wherever you need to.

for example:
![image](https://user-images.githubusercontent.com/24894463/102087768-b2880180-3e22-11eb-97c2-2706ff18d217.png)

**Comment by barnahum8** [comment]
noted 👍
